auth for drivers and payment
MariaBrichkovskaya/cab-aggregator pull request #15
Opened 2024-02-28 10:34 UTC by MariaBrichkovskaya

2024-02-28 11:45 UTC, IvanKiselevichWork requested changes

2024-02-28 11:45 UTC, IvanKiselevichWork commented on driver-service/src/main/resources/db/changelog/v.1.0/changeset/01-changeset-create-drivers-table.xml
> +            <column name="id" type="uuid">
Цель миграций - возможность запустить новую версию приложения на уже существующих данных, поэтому если что-то нужно изменить, нужно не трогать существующие файлы, а сделать новый.

2024-02-28 12:21 UTC, MariaBrichkovskaya commented on driver-service/src/main/resources/db/changelog/v.1.0/changeset/01-changeset-create-drivers-table.xml
> +            <column name="id" type="uuid">
Поняла, в дальнейшем так и буду делать. Просто в данной ситуации у меня водители не были связаны с юзерами и данные были устаревшими, поэтому мне надо было, чтобы таблицы были пустые. И я решила, что так наверное будет быстрее и миграцию переписать и удалить все данные что были, но в будущем все буду делать новые файлы.

2024-03-01 10:58 UTC, IvanKiselevichWork approved these changes

2024-03-04 09:56 UTC, merged