payment-service
MariaBrichkovskaya/cab-aggregator pull request #4
Opened 2023-12-15 10:37 UTC by MariaBrichkovskaya

2023-12-19 14:07 UTC, KirillKostylev requested changes

2023-12-19 14:07 UTC, KirillKostylev commented on payment-service/src/main/java/com/modsen/paymentservice/service/impl/PaymentServiceImpl.java
> +        if(customerRepository.existsById(request.getPassengerId()))
+ Логику проверок можно вынести в отдельный метод
+ Не забывай отформатировать код перед коммитом

2023-12-21 08:08 UTC, KirillKostylev requested changes
Еще один момент, после того как пофиксаешь что-то из коммента, отмечай его как resolved + добавь в коммент done, либо же отпиши в случае вопросов (по необходимости можем обсудить подробнее какие-либо проблемы).
И после того, как отправишь запрос на повторное ревью, пингани меня пожалуйста в тимсе, чтобы ускорить процесс

2023-12-21 08:08 UTC, KirillKostylev commented on payment-service/src/main/java/com/modsen/paymentservice/service/impl/PaymentServiceImpl.java
> +    public CustomerResponse createCustomer(CustomerRequest request) throws StripeException {
Хорошей практикой будет словить StripeException как можно раньше, обработать и прокинуть свой кастомный runtimeException (и точно также в контроллер эдвайсе уже обработаешь свой). И тогда не придется пробрасывать ошибку наверх (что происходит у тебя во многих классах)

2023-12-21 09:12 UTC, MariaBrichkovskaya commented on payment-service/src/main/java/com/modsen/paymentservice/controller/PaymentController.java
> +    @ResponseStatus(HttpStatus.OK)
Done

2023-12-21 09:12 UTC, MariaBrichkovskaya commented on payment-service/src/main/java/com/modsen/paymentservice/service/impl/PaymentServiceImpl.java
> +    public CustomerResponse createCustomer(CustomerRequest request) throws StripeException {
Done

2023-12-21 10:44 UTC, KirillKostylev requested changes

2023-12-21 10:44 UTC, KirillKostylev commented on payment-service/src/main/java/com/modsen/paymentservice/service/impl/PaymentServiceImpl.java
> +        }
Для улучшения читабельности, можешь повыносить вызов методов (которые могут выкинуть ошибку) в отдельные методы. Таким образом, try cach блоки не будут ухудшать читабельность и сами блоки будут маленьких размеров и переиспользоваться  

`
private void checkBalance(String customerId, long amount) {
    Customer customer = retrieveCustomer(customerId);
    // more logic
}

private Customer retrieveCustomer(customerId){
try
 return Customer.retrieve(customerId);
catch
throw exception
}


`

2023-12-21 13:04 UTC, MariaBrichkovskaya commented on payment-service/src/main/java/com/modsen/paymentservice/service/impl/PaymentServiceImpl.java
> +        }
Done

2023-12-21 13:07 UTC, KirillKostylev approved these changes

2023-12-21 13:09 UTC, merged