communication
MariaBrichkovskaya/cab-aggregator pull request #6
Opened 2024-01-01 17:05 UTC by MariaBrichkovskaya

2024-01-05 10:28 UTC, AbandonedScope requested changes

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/exception/handler/RideHandler.java
> +    }
Вот тут у http ответа будут статус коды 200

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/kafka/DriverConsumer.java
> +        if (!rideRepository.findAll().stream().filter(ride -> ride.getDriverId() == null).toList().isEmpty()) {
Вынеси запрос к репозиторию в отдельную переменную/метод

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/kafka/DriverConsumer.java
> +            Ride ride = rideRepository.findAll().stream().filter(rideWithoutDriver -> rideWithoutDriver.getDriverId() == null).toList().get(0);
Пиши цепочки методов с новых строк!

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/kafka/RideProducer.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(RideProducer.class);
А чего так а не через ломбоковскую `@Slf4j` ?

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/kafka/StatusProducer.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(RideProducer.class);
`@Slf4j`

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/RideService.java
> +    RideResponse add(CreateRideRequest request) throws ExecutionException, InterruptedException;
Обрабатывай исключения в этом методе, а не пробрасывай их

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/RideService.java
> +    void update(UpdateRideRequest request, Long id);
Можешь тут возвращать обновлённую сущность

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        return driverFeignClient.getDriver(driverId);
```suggestion
        }
        
        return driverFeignClient.getDriver(driverId);
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +            return null;
Возвращать null не лучший вариант

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        rideProducer.sendMessage(RideRequest.builder().id(rideToSave.getId()).build());
Методы билдера пиши с новых строк

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        Ride ride = rideRepository.findById(request.getRideId()).get();
А если нет такой поездки по id?

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        ride.setRideStatus(RideStatus.ACCEPTED);
Вот это пожалуй можно вынести в отдельный метод

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +    }
Вообще, правильнее приватные методы все размещать после всех публичных, а не "чередовать" их

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +                .currency("BYN").amount(amount)
"BYN" -> в константы или енам вынеси

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +    private double generatePrice() {
лучше назови calcuatePrice, вдруг потом захочешь реально её считать

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        Ride ride = rideRepository.findById(id).orElseThrow(() -> new NotFoundException(id));
`orElseThrow(() -> new NotFoundException(id));` с новой строки должно быть!

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
>      }
Оно не чекает, вернее не только чекает, а ещё и сэтит, переименуй

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +                    return response;
Вообще, это можно вынести в отдельный метод:
+ во первых, ты это не только здесь так делаешь, а значит, так можно избавиться от дублирования кода
+ во вторых, так будет более читаемым `map`

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +                .stream().map(ride -> {
`.stream` должен быть на предыдущей строке, а `.map` уже на новой

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        return RidesListResponse.builder().rides(rides).build();
`.rides(rides)` и `.build();` с новых строк пиши

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        Ride ride = modelMapper.map(request, Ride.class);
```suggestion

        Ride ride = modelMapper.map(request, Ride.class);
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
```suggestion
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
>          }
```suggestion
        }
        
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +                }).toList();
```suggestion
        List<RideResponse> rides = ridesPage.getContent().stream()
                .map(ride -> {
                    RideResponse response = toDto(ride);
                    checkDriver(response, ride.getDriverId());
                    checkPassenger(response, passengerId);
                    return response;
                })
                .toList();
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +                    return response;
Вот это в отдельный метод

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +                }).toList();
То же самое

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
>                  .rides(rides).build();
```suggestion
                .rides(rides)
                .build();
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
>                  .rides(rides).build();
```suggestion
                .rides(rides)
                .build();
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
>          }
Так тебе потом не придётся делать ещё один запрос к бд
```suggestion
        Optional<Ride> optionalRide = rideRepository.findById(id);
        if (optionalRide.isEmpty()) {
            log.error("Ride with id {} was not found", id);
            throw new NotFoundException(id);
        }
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        if (ride.getDriverId()==null){
```suggestion
        if (ride.getDriverId() == null){
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        if (ride.getRideStatus().equals(RideStatus.FINISHED)) {
```suggestion
        if (RideStatus.FINISHED.equals(ride.getRideStatus())) {
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        if (RideStatus.valueOf(statusRequest.getStatus()).equals(RideStatus.FINISHED)) {
```suggestion
        if (RideStatus.FINISHED.toString().equals(statusRequest.getStatus())) {
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +                    .builder().driverId(ride.getDriverId()).build();
```suggestion
            EditDriverStatusRequest driverStatusRequest = EditDriverStatusRequest.builder()
                    .driverId(ride.getDriverId())
                    .build();
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +        rideRepository.save(ride);
```suggestion

        ride.setRideStatus(RideStatus.valueOf(statusRequest.getStatus()));
        rideRepository.save(ride);
```

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/resources/application.yml
> +    change-log: classpath:db/changelog/v.1.0/db.changelog-v.1.0.xml
Почему ссылаешься не на мастер ченджлог а на конкретную версию??

2024-01-05 10:28 UTC, AbandonedScope commented on ride-service/src/main/resources/db/changelog/v.1.0/changeset/01-changeset-create-rides-table.xml
> +            </column>
Думаю, в этих случаях 255 - это слишком много

2024-01-05 15:00 UTC, MariaBrichkovskaya commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
> +            return null;
У некоторых поездок при создании водитель не сетается, так как на момент создания не было свободных. Поэтому в случае, если поездке водитель пока не назначен, я вместо респонса возвращаю null. Как это реализовать иначе у меня нет мыслей.

2024-01-05 15:25 UTC, AbandonedScope requested changes

2024-01-05 15:25 UTC, AbandonedScope commented on driver-service/src/main/java/com/modsen/driverservice/dto/request/DriverForRideRequest.java
> +}
```suggestion
@Builder
public record DriverForRideRequest(
       long driverId,
       long rideId
 ) {
}
```

2024-01-05 15:25 UTC, AbandonedScope commented on driver-service/src/main/java/com/modsen/driverservice/dto/request/EditDriverStatusRequest.java
> +}
```suggestion
public record EditDriverStatusRequest(
      long driverId
) {
}
```

2024-01-05 15:25 UTC, AbandonedScope commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
> +    private DriverResponse toDto(Driver driver) {
Переименуй, теперь это не просто маппинг

2024-01-05 15:25 UTC, AbandonedScope commented on driver-service/src/main/java/com/modsen/driverservice/service/impl/DriverServiceImpl.java
>                  .map(this::toDto).toList();
```suggestion
                .map(this::toDto)
                .toList();
```

2024-01-05 15:25 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exception/handler/PassengerHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
А вдруг там другой статус?

2024-01-05 15:25 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/service/impl/PassengerServiceImpl.java
>          Passenger passenger = passengerRepository.findById(id).orElseThrow(() -> new NotFoundException(id));
```suggestion
        Passenger passenger = passengerRepository.findById(id)
        .orElseThrow(() -> new NotFoundException(id));
```

2024-01-05 15:25 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/service/impl/PassengerServiceImpl.java
>          Passenger passengerToUpdate = passengerRepository.findById(id).orElseThrow(() -> new NotFoundException(id));
```suggestion
        Passenger passengerToUpdate = passengerRepository.findById(id)
        .orElseThrow(() -> new NotFoundException(id));
```

2024-01-05 15:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/controller/RideController.java
> +        RideResponse response=rideService.update(rideRequest, id);
```suggestion
        RideResponse response = rideService.update(rideRequest, id);
```

2024-01-05 15:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/controller/RideController.java
>          return ResponseEntity.ok(MessageResponse.builder().message("Status updated to " + statusRequest.getStatus()).build());
```suggestion
        return ResponseEntity.ok(MessageResponse.builder()
        .message("Status updated to " + statusRequest.getStatus())
        .build()
        );
```

2024-01-05 15:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/kafka/DriverConsumer.java
> +                    .get(0);
```suggestion
            Ride ride = rideRepository
                    .findAll()
                    .stream()
                    .filter(rideWithoutDriver -> rideWithoutDriver.getDriverId() == null)
                    .toList()
                    .get(0);
```
```suggestion
            Ride ride = rideRepository.findAll().stream()
                    .filter(rideWithoutDriver -> rideWithoutDriver.getDriverId() == null)
                    .toList()
                    .get(0);
```

2024-01-05 15:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/kafka/DriverConsumer.java
> +            statusProducer.sendMessage(EditDriverStatusRequest.builder().driverId(driver.getDriverId()).build());
```suggestion
            statusProducer.sendMessage(EditDriverStatusRequest.builder()
            .driverId(driver.getDriverId())
            .build()
            );
```

2024-01-05 15:25 UTC, AbandonedScope commented on ride-service/src/main/java/com/modsen/rideservice/service/impl/RideServiceImpl.java
>                  .toList();
```suggestion
        List<RideResponse> rides = ridePage.getContent().stream()
                .map(this::toDto)
                .toList();
```

2024-01-08 09:59 UTC, AbandonedScope approved these changes

2024-01-08 09:59 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controller/PassengerController.java
> +        return ResponseEntity.ok(response);
Лучше возвращать статус NO_CONTENT, а не OK

2024-01-08 14:58 UTC, merged